# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ytdownloader.ui'
#
# Created: Mon Nov 07 16:26:36 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(474, 327)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(9, 9, 457, 120))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 120))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 20, 431, 77))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.rbUrl = QtGui.QRadioButton(self.layoutWidget)
        self.rbUrl.setObjectName("rbUrl")
        self.gridLayout.addWidget(self.rbUrl, 0, 0, 1, 1)
        self.txtbxUrl = QtGui.QLineEdit(self.layoutWidget)
        self.txtbxUrl.setObjectName("txtbxUrl")
        self.gridLayout.addWidget(self.txtbxUrl, 0, 1, 1, 1)
        self.rbSearch = QtGui.QRadioButton(self.layoutWidget)
        self.rbSearch.setObjectName("rbSearch")
        self.gridLayout.addWidget(self.rbSearch, 1, 0, 1, 1)
        self.txtbxSearch = QtGui.QLineEdit(self.layoutWidget)
        self.txtbxSearch.setObjectName("txtbxSearch")
        self.gridLayout.addWidget(self.txtbxSearch, 1, 1, 1, 1)
        self.btnSearch = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSearch.sizePolicy().hasHeightForWidth())
        self.btnSearch.setSizePolicy(sizePolicy)
        self.btnSearch.setObjectName("btnSearch")
        self.gridLayout.addWidget(self.btnSearch, 2, 1, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(9, 135, 457, 119))
        self.groupBox_2.setObjectName("groupBox_2")
        self.rbDlVideo = QtGui.QRadioButton(self.groupBox_2)
        self.rbDlVideo.setGeometry(QtCore.QRect(10, 50, 111, 17))
        self.rbDlVideo.setObjectName("rbDlVideo")
        self.rbDlAudio = QtGui.QRadioButton(self.groupBox_2)
        self.rbDlAudio.setGeometry(QtCore.QRect(10, 70, 111, 17))
        self.rbDlAudio.setObjectName("rbDlAudio")
        self.splitter = QtGui.QSplitter(self.groupBox_2)
        self.splitter.setGeometry(QtCore.QRect(10, 20, 391, 23))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.btnOutputDir = QtGui.QPushButton(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOutputDir.sizePolicy().hasHeightForWidth())
        self.btnOutputDir.setSizePolicy(sizePolicy)
        self.btnOutputDir.setObjectName("btnOutputDir")
        self.lblOutputDir = QtGui.QLabel(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOutputDir.sizePolicy().hasHeightForWidth())
        self.lblOutputDir.setSizePolicy(sizePolicy)
        self.lblOutputDir.setText("")
        self.lblOutputDir.setObjectName("lblOutputDir")
        self.btnExit = QtGui.QPushButton(self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(390, 260, 75, 23))
        self.btnExit.setObjectName("btnExit")
        self.btnDownload = QtGui.QPushButton(self.centralwidget)
        self.btnDownload.setGeometry(QtCore.QRect(10, 260, 75, 23))
        self.btnDownload.setObjectName("btnDownload")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 474, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.btnExit, QtCore.SIGNAL("clicked()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Youtube Downloader", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Source", None, QtGui.QApplication.UnicodeUTF8))
        self.rbUrl.setText(QtGui.QApplication.translate("MainWindow", "From URL", None, QtGui.QApplication.UnicodeUTF8))
        self.rbSearch.setText(QtGui.QApplication.translate("MainWindow", "From Search Phrase", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSearch.setText(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.rbDlVideo.setText(QtGui.QApplication.translate("MainWindow", "Download Video", None, QtGui.QApplication.UnicodeUTF8))
        self.rbDlAudio.setText(QtGui.QApplication.translate("MainWindow", "Download Audio", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOutputDir.setText(QtGui.QApplication.translate("MainWindow", "Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDownload.setText(QtGui.QApplication.translate("MainWindow", "Download", None, QtGui.QApplication.UnicodeUTF8))

